import { CivicReport } from "./types";

export const DUMMY_REPORTS: CivicReport[] = [
    {
        id: "7Ytt3kLgPkCvxWg3N6pRmz7k2gH1bFx8kFpCadzGkP",
        locationLat: 27.7172,
        locationLng: 85.324,
        district: "Kathmandu",
        wardNumber: 16,
        ipfsCid: "QmPkR2L5d8hFGo8q7iFbnCJgiMvehA2jB5oZg8LC2r6T",
        upvotes: 205,
        isPetition: true,
        reporter: "7Ytt3kLgPkCvxWg3N6pRmz7k2gH1bFx8kFpCadzGkP",
        category: "roads",
        createdAt: Date.now() - 86400000,
        title: "Massive pothole on Ring Road near Kalanki — multiple accidents reported",
        description: "The pothole has been growing for months near the Kalanki intersection. Motorcycles and smaller vehicles are at extreme risk, especially at night when visibility is poor.",
        imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400&h=300&fit=crop",
        status: "petition",
    },
    {
        id: "CoX3bJ8xLsVHfKPQ2dJcHmN5rP9vBx4kFpCadzPv5A",
        locationLat: 27.7085,
        locationLng: 85.3188,
        district: "Kathmandu",
        wardNumber: 4,
        ipfsCid: "QmRkT2L5d8hFGo8q7iFbnCJgiMvehA2jB5oZg8LC3s7U",
        upvotes: 178,
        isPetition: true,
        reporter: "CoX3bJ8xLsVHfKPQ2dJcHmN5rP9vBx4kFpCadzPv5A",
        category: "corruption",
        createdAt: Date.now() - 36000000,
        title: "Ward office demanding illegal fees for citizenship certificates",
        description: "People are being asked to pay Rs 2000-5000 under the table for citizenship certificate processing that should be free. Multiple witnesses have come forward.",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop",
        status: "petition",
    },
    {
        id: "9FgH2kLmPnCvxWg3N6pQrz7k2gH1bFx8kFpCadzRt3",
        locationLat: 28.2096,
        locationLng: 83.9856,
        district: "Kaski",
        wardNumber: 17,
        ipfsCid: "QmUnW5O8g1kIr1t0lIeeFMliPxhiD5mE8rCj1OF6v0X",
        upvotes: 147,
        isPetition: true,
        reporter: "9FgH2kLmPnCvxWg3N6pQrz7k2gH1bFx8kFpCadzRt3",
        category: "utilities",
        createdAt: Date.now() - 18000000,
        title: "Illegal factory dumping waste into Seti River — broken water pipes flooding streets",
        description: "Chemical waste from an unregistered factory is leaking through broken municipal pipes directly into the Seti River. Dead fish spotted along 2km stretch. Water supply contaminated.",
        imageUrl: "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=400&h=300&fit=crop",
        status: "petition",
    },
    {
        id: "5BnM7rLkPxCvyWh4O7qStz8l3hI2cGy9lGqDbezSu4",
        locationLat: 26.6682,
        locationLng: 87.2836,
        district: "Morang",
        wardNumber: 11,
        ipfsCid: "QmSlU3M6e9iGHp9r8jGcnDKjhNwfhB3kC6pAh9MD4t8V",
        upvotes: 132,
        isPetition: true,
        reporter: "5BnM7rLkPxCvyWh4O7qStz8l3hI2cGy9lGqDbezSu4",
        category: "scam",
        createdAt: Date.now() - 21600000,
        title: "Fake employment agency scamming migrant workers near bus park",
        description: "An office near the Biratnagar bus park is collecting Rs 50,000-100,000 from workers promising Gulf jobs. Multiple victims confirmed — no actual visa processing happening.",
        imageUrl: "https://images.unsplash.com/photo-1521791055366-0d553872125f?w=400&h=300&fit=crop",
        status: "petition",
    },
    {
        id: "4AmL6qKjOwBuxVg3N6pRsy7j2fH0aEw8jFoCcbyRt3",
        locationLat: 27.672,
        locationLng: 85.4298,
        district: "Bhaktapur",
        wardNumber: 8,
        ipfsCid: "QmTmV4N7f0jIHq0s9kHdoELkhOxgiC4lD7qBi0NE5u9W",
        upvotes: 91,
        isPetition: false,
        reporter: "4AmL6qKjOwBuxVg3N6pRsy7j2fH0aEw8jFoCcbyRt3",
        category: "hazards",
        createdAt: Date.now() - 14400000,
        title: "Collapsed retaining wall blocking Arniko Highway — landslide risk",
        description: "Heavy rainfall caused a 30-meter retaining wall to collapse on the highway. Landslide risk is high. Only one lane is passable. Heavy vehicles being diverted through narrow village roads.",
        imageUrl: "https://images.unsplash.com/photo-1582407947092-50b8c1a4f3e8?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "3ZlK5pJiNvAtxUf2M5oQrx6i1eG9zDv7iEnBbaXqS2",
        locationLat: 27.6588,
        locationLng: 84.4364,
        district: "Chitwan",
        wardNumber: 5,
        ipfsCid: "QmVoX6P9h2lJs2u1mJfgGNmjQyiF6nFs9sDk2PG7w1Y",
        upvotes: 87,
        isPetition: false,
        reporter: "3ZlK5pJiNvAtxUf2M5oQrx6i1eG9zDv7iEnBbaXqS2",
        category: "utilities",
        createdAt: Date.now() - 43200000,
        title: "Open waste burning site — uncollected garbage near residential area in Bharatpur",
        description: "Municipality is burning uncollected waste in an open field adjacent to a school and residential colony. Thick smoke visible daily from 6-9 AM. Children complaining of breathing problems.",
        imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "2YkJ4oIhMuZswTe1L4nPqw5h0dF8yCu6hDmAaZWpR1",
        locationLat: 27.6769,
        locationLng: 85.3157,
        district: "Lalitpur",
        wardNumber: 12,
        ipfsCid: "QmWpY7Q0i3mKt3v2nKgeHOnkRzjG7oGt0eFl3QH8x2Z",
        upvotes: 64,
        isPetition: false,
        reporter: "2YkJ4oIhMuZswTe1L4nPqw5h0dF8yCu6hDmAaZWpR1",
        category: "roads",
        createdAt: Date.now() - 64800000,
        title: "Crater-sized potholes on Satdobato-Godawari road",
        description: "Multiple deep potholes along the main road to Godawari. At least 3 motorcycle accidents this week. Road has not been repaired despite multiple complaints to ward office.",
        imageUrl: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "6DfE0mGfKsXquRc9J2lNot3f8bD6wAs4fBkyYXUnP9",
        locationLat: 27.5831,
        locationLng: 83.5444,
        district: "Rupandehi",
        wardNumber: 2,
        ipfsCid: "QmXqZ8R1j4nLu4w3oLhfIPomSzkH8pHu1gGm4RI9y3A",
        upvotes: 42,
        isPetition: false,
        reporter: "6DfE0mGfKsXquRc9J2lNot3f8bD6wAs4fBkyYXUnP9",
        category: "roads",
        createdAt: Date.now() - 7200000,
        title: "Broken bridge on Siddhartha Highway poses danger to commuters",
        description: "The steel railing and concrete surface of the bridge are severely damaged. Heavy vehicles still crossing despite visible structural cracks. Bridge is over 30 years old with no maintenance.",
        imageUrl: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "1CeD9lFeLrWptQb8I1kMns2e7aC5vZr3eAjxXWTmO8",
        locationLat: 27.6205,
        locationLng: 85.5392,
        district: "Kavrepalanchok",
        wardNumber: 9,
        ipfsCid: "QmYrA9S2k5oMv5x4pMigJQnlTziI9qIv2hHn5SJ0z4B",
        upvotes: 34,
        isPetition: false,
        reporter: "1CeD9lFeLrWptQb8I1kMns2e7aC5vZr3eAjxXWTmO8",
        category: "corruption",
        createdAt: Date.now() - 1800000,
        title: "Land registration office demanding bribes for document processing",
        description: "Officers at the malpot office are openly asking for Rs 5000-10000 to process land registration papers. Normal processing delayed indefinitely without payment.",
        imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "0BdC8kEdKqVosPA7H0jLmr1d6zB4uYq2dZiwWVSlN7",
        locationLat: 28.2024,
        locationLng: 81.6271,
        district: "Banke",
        wardNumber: 14,
        ipfsCid: "QmZsB0T3l6pNw6y5qNjhKRomUzkJ0rJw3iIo6TK1a5C",
        upvotes: 23,
        isPetition: false,
        reporter: "0BdC8kEdKqVosPA7H0jLmr1d6zB4uYq2dZiwWVSlN7",
        category: "scam",
        createdAt: Date.now() - 10800000,
        title: "Counterfeit medicine being sold at unlicensed clinic",
        description: "A clinic operating without a valid license is selling expired and counterfeit medicines to patients. Multiple people reported adverse reactions after taking the medication.",
        imageUrl: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop",
        status: "active",
    },
    {
        id: "ZAcB7jDcJpUnnOz6G9iKlq0c5yA3tXp1cYhvVUrkM6",
        locationLat: 29.2953,
        locationLng: 80.588,
        district: "Darchula",
        wardNumber: 3,
        ipfsCid: "QmAtC1U4m7qOx7z6rOkhLSqnVakK1sKx4jJp7UK2b6D",
        upvotes: 15,
        isPetition: false,
        reporter: "ZAcB7jDcJpUnnOz6G9iKlq0c5yA3tXp1cYhvVUrkM6",
        category: "hazards",
        createdAt: Date.now() - 28800000,
        title: "Flood embankment construction stalled — flooding risk as monsoon approaches",
        description: "Construction of the flood embankment was halted 6 months ago at 40% completion. The contractor has disappeared. With monsoon approaching, serious flooding risk — hundreds of families at danger.",
        imageUrl: "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&h=300&fit=crop",
        status: "active",
    },
];
